version: "3"
services:
  es01:
    image: ghcr.io/codelibs/fess-elasticsearch:7.14.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - esdictionary01:/usr/share/elasticsearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - esnet
    depends_on:
      - es02
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  es02:
    image: ghcr.io/codelibs/fess-elasticsearch:7.14.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - esdictionary02:/usr/share/elasticsearch/config/dictionary
    ports:
      - 9201:9200
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - es01
  fess01:
    image: ghcr.io/codelibs/fess:13.14.0
    container_name: fess01
    environment:
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
      - "FESS_JAVA_OPTS=-Dfess.config.scheduler.target.name=fess01"
    ports:
      - "8080:8080"
    networks:
      - esnet
    depends_on:
      - es01
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  fess02:
    image: ghcr.io/codelibs/fess:13.14.0
    container_name: fess02
    environment:
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
      - "FESS_JAVA_OPTS=-Dfess.config.scheduler.target.name=fess02"
    ports:
      - "8081:8080"
    networks:
      - esnet
    depends_on:
      - es01
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    depends_on:
      - fess01
    networks:
      - esnet
networks:
  esnet:
    driver: bridge
volumes:
  esdata01:
    driver: local
  esdictionary01:
    driver: local
  esdata02:
    driver: local
  esdictionary02:
    driver: local
